# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: atomix/headers/headers.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from atomix.proto import primitive


class ResponseType(betterproto.Enum):
    RESPONSE = 0
    OPEN_STREAM = 1
    CLOSE_STREAM = 2


class ResponseStatus(betterproto.Enum):
    OK = 0
    ERROR = 1
    NOT_LEADER = 2


@dataclass
class RequestHeader(betterproto.Message):
    partition: int = betterproto.int32_field(6)
    primitive: primitive.PrimitiveId = betterproto.message_field(1)
    session_id: int = betterproto.uint64_field(2)
    request_id: int = betterproto.uint64_field(3)
    index: int = betterproto.uint64_field(4)
    streams: List["StreamHeader"] = betterproto.message_field(5)


@dataclass
class ResponseHeader(betterproto.Message):
    session_id: int = betterproto.uint64_field(1)
    stream_id: int = betterproto.uint64_field(2)
    response_id: int = betterproto.uint64_field(3)
    index: int = betterproto.uint64_field(4)
    leader: str = betterproto.string_field(5)
    status: "ResponseStatus" = betterproto.enum_field(6)
    type: "ResponseType" = betterproto.enum_field(7)


@dataclass
class StreamHeader(betterproto.Message):
    stream_id: int = betterproto.uint64_field(1)
    response_id: int = betterproto.uint64_field(2)
